name: continuous
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build Pantry.sln --configuration Release --no-restore
      - name: Run unit tests
        run: dotnet test ./tests/Pantry.Tests.Component/Pantry.Tests.Component.csproj --configuration Release --no-build --verbosity normal --logger trx --filter "Category=Unit"
      - name: Run integration tests
        run: dotnet test ./tests/Pantry.Tests.Component/Pantry.Tests.Component.csproj --configuration Release --no-build --verbosity normal --logger trx --filter "Category=Integration"
      - name: Publish tests report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: .NET Tests
          path: "**/*.trx"
          reporter: dotnet-trx
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore --runtime linux-musl-x64
      - name: Build
        run: dotnet build ./src/Pantry.Service/Pantry.Service.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./src/Pantry.Service/Pantry.Service.csproj --configuration Release -o app/publish --no-restore --runtime linux-musl-x64 --no-self-contained
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: app/publish/
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: published-app
          path: /src/Pantry.Service/app/publish
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: mbi050643/pantry

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./src/Pantry.Service
          file: src/Pantry.Service//Dockerfile
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
