name: deploy
on:
  push:
    branches:
      - main
  # the 1st condition
  # workflow_run:
  #   workflows: ["continuous"]
  #   branches: [main]
  #   types:
  #     - completed
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    # the 2nd condition
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Restore
        run: dotnet restore --runtime linux-musl-x64
      - name: Build
        run: dotnet build ./src/Pantry.Service/Pantry.Service.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./src/Pantry.Service/Pantry.Service.csproj --configuration Release -o app/publish --no-restore --runtime linux-musl-x64 --no-self-contained
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: app/publish/
      - name: Jelastic CLI
        # uses: abhisek91/github-actions-jelastic@v2
        uses: DovnarAlexander/github-actions-jelastic@master
        with:
          jelastic_url:  ${{ secrets.JELASTIC_URL }}
          jelastic_username: ${{ secrets.JELASTIC_USERNAME }}
          jelastic_password: ${{ secrets.JELASTIC_TOKEN }}
          task: environment/deployment/deployarchive --envName ${{ secrets.JELASTIC_ENV_NAME }} --nodeGroup cp --fileUrl https://nightly.link/TSBE/${{ GITHUB_REPOSITORY }}/workflows/deploy/main/published-app.zip --fileName published-app.zip
